name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./myapp

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/borkday:latest .
        working-directory: ./myapp

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/borkday:latest

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Set Railway Variables
        run: |
          railway env set CLIENT_ID ${{ secrets.CLIENT_ID }}
          railway env set DISCORD_TOKEN ${{ secrets.DISCORD_TOKEN }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up --service borkday
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
